### ISSUE TITLE
add yaml support for hysds-io and job_specs

### ISSUE THREAD

**Issue by DustinKLo** [hysds/hysds_commons#56]
`job_spec` example:
```json
{
  "command":"/home/ops/ariamh/ariaml/extractFeatures.sh",
  "disk_usage":"1GB",
  "imported_worker_files": {
    "/home/ops/.netrc": "/home/ops/.netrc",
    "/home/ops/.aws": "/home/ops/.aws",
    "/home/ops/ariamh/conf/settings.conf": "/home/ops/ariamh/conf/settings.conf"
  },
  "disable_pre_builtins": true,
  "params" : [
    {
      "name": "uri",
      "destination": "positional"
    },
    {
      "name": "uri",
      "destination": "localize"
    }
  ]
}
```

`hysds-io` example:
```json
{
  "params" : [
    {
      "name": "localize_product_trigger",
      "from": "dataset_jpath:urls.0"
    },
    {
      "name": "scene_list",
      "from": "value",
      "value":"http://landsat-pds.s3.amazonaws.com/scene_list.gz"
    },
    {
      "name": "id",
      "from": "dataset_jpath:objectid"
    },
    {
      "name": "acq_time",
      "from": "dataset_jpath:metadata.acq_time"
    }
  ]
}
```

as of right now HySDS only supports json formatting for hysds-ios and job_spec. however JSON has script formatting:
- no comments
- no trailing commas

in the future it would be helpful to add YAML support, as YAML supports comments and such, ex:
```yaml
---
command: "/home/ops/ariamh/ariaml/extractFeatures.sh"
disk_usage: 1GB
imported_worker_files:
  "/home/ops/.netrc": "/home/ops/.netrc"
  "/home/ops/.aws": "/home/ops/.aws"
  "/home/ops/ariamh/conf/settings.conf": "/home/ops/ariamh/conf/settings.conf"
disable_pre_builtins: true
params:
  - name: uri
    destination: positional
  - name: uri
    destination: localize

```
